import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import HeaderTop from '@/components/HeaderTop'
import HeaderMain from '@/components/HeaderMain'
import NavBar from '@/components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderTop/>
        <HeaderMain/>
        <NavBar/>
        {children}</body>
    </html>
  )
}
